### ISSUE TITLE
Capitalisation of contentID vs contentId

### ISSUE THREAD

**Issue by nacnudus** [alphagov/govuk-knowledge-graph-search#18]
I haven't checked that this is really a bug, but I think `contentID` must be `contentId` otherwise it will silently return `null`.

https://github.com/alphagov/govuk-knowledge-graph-search/blob/f5c9804c11160f4209479cac679073bb5d76fd2f/src/ts/neo4j.ts#L423

**Comment by maxf** [comment]
yes it was a bug. Fixed in 6e34be7
