### ISSUE TITLE
Bug: can't do advanced search without keywords

### ISSUE THREAD

**Issue by maxf** [alphagov/govuk-knowledge-graph-search#56]
https://trello.com/c/7qi16AUA/2248-allow-search-without-keywords

If you want to show all pages that are published using Specialist Publisher you would normally go to Advanced search, select Publisher and click Search. But that does nothing.

This is because search won't start if the keywords field is empty, which is a bug. A workaround is to just enter a whitespace in the field, but a proper fix would be to allow search to run even with an empty keywords field.

**Comment by nacnudus** [comment]
I can no longer reproduce this bug.

https://gov-search.service.gov.uk/?link-search-url=youtube&search-type=advanced
